/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PriDashboardRouteImport } from './routes/pri/dashboard'
import { Route as UniversityDashboardRouteImport } from './routes/university/dashboard'
import { Route as GovernmentDepartmentDashboardRouteImport } from './routes/government/department/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PriDashboardRoute = PriDashboardRouteImport.update({
  id: '/pri/dashboard',
  path: '/pri/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityDashboardRoute = UniversityDashboardRouteImport.update({
  id: '/university/dashboard',
  path: '/university/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentDepartmentDashboardRoute =
  GovernmentDepartmentDashboardRouteImport.update({
    id: '/government/department/dashboard',
    path: '/government/department/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pri/dashboard': typeof PriDashboardRoute
  '/university/dashboard': typeof UniversityDashboardRoute
  '/government/department/dashboard': typeof GovernmentDepartmentDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pri/dashboard': typeof PriDashboardRoute
  '/university/dashboard': typeof UniversityDashboardRoute
  '/government/department/dashboard': typeof GovernmentDepartmentDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pri/dashboard': typeof PriDashboardRoute
  '/university/dashboard': typeof UniversityDashboardRoute
  '/government/department/dashboard': typeof GovernmentDepartmentDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pri/dashboard'
    | '/university/dashboard'
    | '/government/department/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pri/dashboard'
    | '/university/dashboard'
    | '/government/department/dashboard'
  id:
    | '__root__'
    | '/'
    | '/pri/dashboard'
    | '/university/dashboard'
    | '/government/department/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PriDashboardRoute: typeof PriDashboardRoute
  UniversityDashboardRoute: typeof UniversityDashboardRoute
  GovernmentDepartmentDashboardRoute: typeof GovernmentDepartmentDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pri/dashboard': {
      id: '/pri/dashboard'
      path: '/pri/dashboard'
      fullPath: '/pri/dashboard'
      preLoaderRoute: typeof PriDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university/dashboard': {
      id: '/university/dashboard'
      path: '/university/dashboard'
      fullPath: '/university/dashboard'
      preLoaderRoute: typeof UniversityDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government/department/dashboard': {
      id: '/government/department/dashboard'
      path: '/government/department/dashboard'
      fullPath: '/government/department/dashboard'
      preLoaderRoute: typeof GovernmentDepartmentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PriDashboardRoute: PriDashboardRoute,
  UniversityDashboardRoute: UniversityDashboardRoute,
  GovernmentDepartmentDashboardRoute: GovernmentDepartmentDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
